title: BZFlag Plugin Starter
description: >
  An opinionated but useful tool to generate the skeleton for a BZFlag
  plugin.
baseurl: /bzflagPluginStarter2

collections:
  - events
  - licenses

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - lib/
  - README.md
  - LICENSE.md

# Development settings
livereload: true
