title: BZFlag Plugin Starter
description: >
  An opinionated but useful tool to generate the skeleton for a BZFlag
  plugin.
baseurl: ""

collections:
  - events

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
