title: BZFlag Plugin Starter
description: >
  An opinionated but useful tool to generate the skeleton for a BZFlag plugin.
baseurl: /

collections:
  - events
  - licenses

google_analytics: UA-59480871-2

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - lib/
  - README.md
  - LICENSE.md
  - tools/
  - Makefile
  - node_modules

# Development settings
livereload: true
