[build]
  publish = "app/"
  command = "make build"

[[redirects]]
  from = "https://bz-plugin-starter.projects.allejo.io/*"
  to = "https://bzflag-plugin-starter.allejo.org/:splat"
  status = 301
  force = true
